export const SHOW_REGISTRATION = 'SHOW_REGISTRATION';
export const INPUT_USERNAME = 'INPUT_USERNAME';
export const INPUT_USER_BIRTHDATE = 'INPUT_USER_BIRTHDATE';
export const INPUT_USER_EMAIL = 'INPUT_USER_EMAIL';
export const INPUT_USER_PASSWORD = 'INPUT_USER_PASSWORD';
export const USERS_ARRAY = 'USERS_ARRAY';
