export const SHOW_REGISTRATION = 'SHOW_REGISTRATION';
export const SHOW_LOG_IN = 'SHOW_LOG_IN';
export const AUTHORIZATION_FLAG = 'AUTHORIZATION_FLAG';
export const USERS_ARRAY = 'USERS_ARRAY';
export const CURRENT_USER = 'CURRENT_USER';
export const CHECK_LOG_AND_PASS = 'CHECK_LOG_AND_PASS';
